import Anthropic from '@anthropic-ai/sdk';
import fs from 'fs-extra';
import path from 'path';
import slugify from 'slugify';

interface JobConfig {
  prompts: string[];
  outputDir: string;
  onProgress?: (current: number, total: number, status: string) => void;
  onComplete?: (results: JobResult[]) => void;
}

interface JobResult {
  prompt: string;
  response: string;
  filename: string;
  success: boolean;
  error?: string;
}

export class ClaudeWorker {
  private client: Anthropic | null = null;
  private apiKey: string;
  private isDemoMode: boolean;

  constructor() {
    this.apiKey = process.env.CLAUDE_API_KEY || process.env.CLAUDE_COOKIE || '';
    this.isDemoMode = !this.apiKey || this.apiKey === 'demo_mode';
    
    if (this.isDemoMode) {
      console.log('🎭 DEMO mode enabled (no Claude API key provided)');
    } else {
      console.log('🔑 Claude API mode enabled');
    }
  }

  async init(): Promise<void> {
    console.log('🚀 Initializing Claude worker...');
    
    if (this.isDemoMode) {
      console.log('🎭 DEMO mode: simulating responses');
      return;
    }

    try {
      this.client = new Anthropic({
        apiKey: this.apiKey,
      });
      
      // Test rapide de la clé API
      console.log('🧪 Testing Claude API connection...');
      await this.client.messages.create({
        model: 'claude-3-5-sonnet-20241022',
        max_tokens: 10,
        messages: [{ role: 'user', content: 'Test' }],
      });
      
      console.log('✅ Claude worker initialized successfully');
    } catch (error) {
      console.error('❌ Claude API initialization error:', error);
      throw new Error('Unable to connect to Claude API. Check your API key.');
    }
  }

  async runJob(config: JobConfig): Promise<JobResult[]> {
    const results: JobResult[] = [];
    const { prompts, outputDir, onProgress } = config;

    // Assurer que le dossier de sortie existe
    await fs.ensureDir(outputDir);

    console.log(`📂 Processing ${prompts.length} prompts...`);

    for (let i = 0; i < prompts.length; i++) {
      const prompt = prompts[i];
      onProgress?.(i + 1, prompts.length, `Processing prompt ${i + 1}/${prompts.length}`);

      try {
        const result = this.isDemoMode 
          ? await this.processDemoPrompt(prompt, outputDir, i + 1, prompts.length)
          : await this.processPrompt(prompt, outputDir);
        
        results.push(result);
        console.log(`✅ Prompt ${i + 1}/${prompts.length} processed successfully`);
      } catch (error) {
        const errorResult: JobResult = {
          prompt,
          response: '',
          filename: '',
          success: false,
          error: error instanceof Error ? error.message : 'Unknown error',
        };
        results.push(errorResult);
        console.error(`❌ Error processing prompt ${i + 1}:`, error);
      }

      // Pause entre les requêtes pour éviter le rate limiting
      if (i < prompts.length - 1) {
        await this.delay(1000);
      }
    }

    config.onComplete?.(results);
    return results;
  }

  private async processDemoPrompt(prompt: string, outputDir: string, current: number, total: number): Promise<JobResult> {
    // Simulation d'une vraie requête API avec délais réalistes
    await this.delay(800); // Simulation temps réseau
    
    // Simulation "Claude qui réfléchit et génère"
    await this.delay(2500);
    
    // Génerer une réponse DEMO réaliste
    const demoResponse = `# Generated Documentation (DEMO Mode)

## Processed Prompt
${prompt}

## Response simulated by Claude Doc Bot

This is a demonstration response. In real mode, this documentation would be generated by Claude 3.5 Sonnet via Anthropic's official API.

### Demonstrated Features:
- ✅ Complete user interface
- ✅ Real-time progress via WebSocket
- ✅ Live log streaming
- ✅ File generation and saving
- ✅ Instant downloads

### Technical Architecture:
- **Claude API**: Replaced Playwright with official API
- **Faster**: ~3 seconds per prompt vs 30+ with Playwright  
- **More reliable**: No dependency on web interface
- **More scalable**: API rate limits handled automatically

### To enable real mode:
1. Add your Claude API key in .env:
   \`\`\`
   CLAUDE_API_KEY=sk-ant-api03-your-key-here
   \`\`\`
2. Restart the application
3. Enjoy ultra-fast automation! ⚡

---
*Generated on ${new Date().toLocaleString('en-US')} - Prompt ${current}/${total}*
*In real mode, this content would be produced by Claude 3.5 Sonnet*`;

    // Générer le nom de fichier en anglais
    const slug = slugify(`demo-${current}-${prompt.substring(0, 30)}`, { lower: true, strict: true });
    const filename = `${slug}.md`;
    const filepath = path.join(outputDir, filename);

    // Sauvegarder le fichier demo
    await fs.writeFile(filepath, demoResponse, 'utf-8');

    return {
      prompt,
      response: demoResponse,
      filename,
      success: true,
    };
  }

  private async processPrompt(prompt: string, outputDir: string): Promise<JobResult> {
    if (!this.client) throw new Error('Claude client not initialized');

    try {
      console.log('🤖 Sending prompt to Claude via API...');
      
      const message = await this.client.messages.create({
        model: 'claude-3-5-sonnet-20241022',
        max_tokens: 4000,
        temperature: 0.7,
        messages: [
          {
            role: 'user',
            content: `You are a technical documentation expert. Here is the prompt to process:

${prompt}

Generate complete, well-structured and professional documentation in Markdown format. Be precise, detailed and include practical examples when relevant.`
          }
        ],
      });

      const response = message.content[0].type === 'text' ? message.content[0].text : '';

      if (!response.trim()) {
        throw new Error('No response received from Claude API');
      }

      // Générer le nom de fichier à partir du prompt
      const slug = slugify(prompt.substring(0, 50), { lower: true, strict: true });
      const filename = `${slug}.md`;
      const filepath = path.join(outputDir, filename);

      // Sauvegarder la réponse avec un en-tête
      const content = `# Prompt
${prompt}

# Documentation generated by Claude

${response}

---
*Generated on ${new Date().toLocaleString('en-US')} by Claude 3.5 Sonnet via API*`;

      await fs.writeFile(filepath, content, 'utf-8');

      return {
        prompt,
        response,
        filename,
        success: true,
      };

    } catch (error) {
      console.error('Claude API error:', error);
      throw error;
    }
  }

  private delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  async cleanup(): Promise<void> {
    // Plus besoin de nettoyer un navigateur !
    console.log('🧹 Worker cleaned up');
  }
}

// API pour l'utilisation en CLI ou via l'API
export async function runClaudeJob(promptFiles: string[], outputDir: string = './outputs'): Promise<JobResult[]> {
  const worker = new ClaudeWorker();
  
  try {
    await worker.init();
    
    // Charger les prompts depuis les fichiers
    const prompts: string[] = [];
    for (const file of promptFiles) {
      const content = await fs.readFile(file, 'utf-8');
      prompts.push(content.trim());
    }

    const results = await worker.runJob({
      prompts,
      outputDir,
      onProgress: (current, total, status) => {
        console.log(`[${current}/${total}] ${status}`);
      },
    });

    return results;
  } finally {
    await worker.cleanup();
  }
}

// Point d'entrée CLI
if (import.meta.url === `file://${process.argv[1]}`) {
  const promptDir = process.argv[2] || './prompts';
  const outputDir = process.argv[3] || './outputs';

  (async () => {
    try {
      // Lister tous les fichiers .txt dans le dossier prompts
      const files = await fs.readdir(promptDir);
      const promptFiles = files
        .filter(f => f.endsWith('.txt'))
        .map(f => path.join(promptDir, f));

      if (promptFiles.length === 0) {
        console.error('❌ Aucun fichier .txt trouvé dans', promptDir);
        process.exit(1);
      }

      console.log(`🎯 ${promptFiles.length} fichiers de prompts trouvés`);
      const results = await runClaudeJob(promptFiles, outputDir);
      
      const successful = results.filter(r => r.success).length;
      console.log(`✨ Job terminé: ${successful}/${results.length} prompts traités avec succès`);
      
      if (successful < results.length) {
        process.exit(1);
      }
    } catch (error) {
      console.error('💥 Erreur fatale:', error);
      process.exit(1);
    }
  })();
} 